### ISSUE TITLE
Summarize total resource consumption over all PIDs

### ISSUE THREAD

**Issue by asmacdo** [con/duct#39]
Since gathering maxes for each sample and then totaling at report generation time will overestimate usage, instead we will collect "totals" for each sample, but only report the spikes.

**Comment by yarikoptic** [comment]
I think it would be useful to have "average cpu%" probably more than "max cpu%" (spike) since that one I think most of them time would be some 100%. Average is a `sum/number_of` so you can keep adding and also keep track (increment number) on how many times you added to come up with a mean.  The same could be done for memory (although there average is less useful but still might be)

**Comment by asmacdo** [comment]
Added a separate issue for averages
